# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lowtechgmbhbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17 (Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven
      run: mvn clean install -DskipTests


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fb82d738c48449b19376a3fb7ab12a44 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c27da07385254002962721d3338d540d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/zainhanif73/lowtechgmbh-backend:${{ github.sha }}
        context: .
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lowtechgmbhbackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_50968591d484423db4be35d5c899cf6a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fb82d738c48449b19376a3fb7ab12a44 }}/zainhanif73/lowtechgmbh-backend:${{ github.sha }}'
