name: Build and deploy container app to Azure Web App - lowtechgmbh-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    # Step to set up Java (assuming you're using Maven to build the JAR)
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    # Step to build the JAR file
    - name: Build the JAR file
      run: |
        mvn clean install  # or gradle build if using Gradle

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9eac888fe65240a381b00f0b2bfbe492 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2e93c03605fd4921b6b5828b3e94ef1f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9eac888fe65240a381b00f0b2bfbe492 }}/lowtechgmbh-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lowtechgmbh-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_67b85039c2644c79986df26c83baae35 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9eac888fe65240a381b00f0b2bfbe492 }}/lowtechgmbh-backend:${{ github.sha }}'
